name : test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gradle-check:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /opt/jdk
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        run: |
          sudo mkdir -p /opt/jdk
          curl --proto '=https' --tlsv1.2 -sSfL https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/21.3.0-dev-20210824_2253/graalvm-ce-java17-linux-amd64-dev.tar.gz | sudo tar --strip-components=1 -xzvC /opt/jdk
          sudo ln -s /opt/jdk/bin/* /usr/local/bin
      #- uses: actions/setup-java@v1
      #  with:
      #    java-version: '17-ea'
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: check --info --no-daemon --stacktrace --warning-mode all
          # arguments: jar --info --no-daemon --stacktrace --warning-mode all
      - uses: eskatos/gradle-command-action@v1
        if: github.repository == 'aya-prover/aya-dev'
        with:
          dependencies-cache-enabled: true
          arguments: githubActions --info --no-daemon --stacktrace --warning-mode all
          # arguments: :lsp:jlink --info --no-daemon --stacktrace --warning-mode all
      - uses: actions/upload-artifact@master
        if: github.repository == 'aya-prover/aya-dev'
        with:
          name: nightly-build
          path : ./lsp/build/image
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: github.repository == 'aya-prover/aya-dev'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/reports/
          path_to_write_report: ./build/codecov_report.txt
          verbose: true
