name : test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gradle-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16'
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: check --info --no-daemon --stacktrace --warning-mode all
      - uses: eskatos/gradle-command-action@v1
        if: github.repository == 'aya-prover/aya-dev'
        with:
          dependencies-cache-enabled: true
          arguments: githubActions --info --no-daemon --stacktrace --warning-mode all
      - uses: actions/upload-artifact@master
        if: github.repository == 'aya-prover/aya-dev'
        with:
          name: nightly-build
          path : .\lsp\build\image
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: github.repository == 'aya-prover/aya-dev'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .\build\reports\
          path_to_write_report: .\build\codecov_report.txt
          verbose: true
